# Path to your oh-my-zsh configuration.
ZSH=/usr/share/oh-my-zsh/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mod_ienchev"


# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export ALTERNATE_EDITOR=gvim EDITOR=gvim VISUAL=gvim

# emacs
# export EDITOR="emacsclient -t -n"
alias ec='emacsclient -n'
alias et='emacsclient -t'

alias vi='vim'
ecs() { emacsclient -n "/sudo::$*" }
ets() { emacsclient -t "/sudo::$*" }
# 
alias -g '...'='../..'
alias -g '....'='../../..'
alias startx='startx > ~/.Xoutput'
alias mount_storage='sudo mount -t ntfs /dev/sdb2 /media/storage'
alias xvnc='x11vnc -display :0 -rfbauth ~/.x11vnc/passwd -clip 1920x1080+0+0 -scale 1600x900'
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
